### ISSUE TITLE
Should properties.py contains the values used as convergence criteria during the geop?

### ISSUE THREAD

**Issue by grhawk** [epfl-cosmo/i-pi-dev#139]
Is there any way to print out the values used to define if a geometry optimization is converged or not?

**Comment by ceriottm** [comment]
Again, in general I think we should make better use of the output. I
dislike the approach of many ab initio codes of putting *everything* there,
but it's true that there are some diagnostics for which a log file is the
best destination.
I'd say that the "default output" for a GEOP run may be a textual
"convergence report" together with energy, forces and positions at the last
step.
But again, this should be looked after at a later stage, after we have
cleaned up the mess of feature branches that is around. I want ideally to
merge at least dynmatrix, suzukichin and fastxyz -- the latter in
particular since it is a prerequisite for the ppi estimator branch that I'm
quite keen on having delivered.

**Comment by grhawk** [comment]
Moved to the general output issues #151
