### ISSUE TITLE
(re-)Starting with unittests

### ISSUE THREAD

**Issue by grhawk** [epfl-cosmo/i-pi-dev#143]
Hello,

Doing some tests on some part of the code, for different purposes than debugging, I thought it would be a good idea if we start writing some unit tests. Often when writing the code one needs to check that the code does what he expects. This can be structuralized within some "test" file instead of just printing the value of some variable in the screen. The advantages are many: mainly you will write clearer and better-structured code; the code will be easier to understand if you already know what are the expected values of the variables for a given input and, probably the most useful, you can change what you did years ago without (almost) any risks of breaking the code in an unexpected way.  Just write "test driven development" on google and see the examples of what I am saying... (even if our approach will be much softer than test-driven).

That said... I noticed that there are already some tests in the ipi/tests directory. I think, looking at the README, those tests were written with nose in mind. Today, nose is a little bit old, I am not sure if it is still maintained, however, on their website they suggest to switch to nose2.  I would suggest switching directly to py.test. The main advantage is that py.test is a very powerful unittesting framework, at the same time it is easy to use for simple stuff (normal python code with function's name starting with 'test') and avoid boilerplate code. Moreover, the already written tests work without any problems also with py.test.

If everyone is fine with this I would go on to create some tests (on the code I am writing/studying) and some template that everyone can use to add tests... 

Of course, the idea of this post/issue is to discuss on which is the best unittest framework and how to start the unittesting in i-pi...

More technical issue: usually, if I understood correctly, are held in a parallel tree of the main program. I would suggest to create an `ipi-tests` directory at the root level and write tests inside mimicking the `ipi` tree.

**Comment by tomspur** [comment]
> Moreover, the already written tests work without any problems also with py.test.

So it shouldn't matter much if you are using nose or py.test? Nose is still widely in use out there, so I would not consider it dead, yet.

> More technical issue: usually, if I understood correctly, are held in a parallel tree of the main program. I would suggest to create an ipi-tests directory at the root level and write tests inside mimicking the ipi tree.

Putting them into the `ipi` package is of advantage, so that plain python can also find the tests subdirectory. This way it is easy to test everywhere with a single line of code, such as explained e.g. [here](http://matplotlib.org/devel/testing.html):
`python -c "import matplotlib; matplotlib.test()"`

This can also be easy implemented for `ipi`, too.

**Comment by grhawk** [comment]
> Moreover, the already written tests work without any problems also with py.test.
> So it shouldn't matter much if you are using nose or py.test? Nose is still widely in use out there, so I would not consider it dead, yet.

Actually it matter in the sense that py.test is easier to use and avoid the boilerplate code... moreover, "not be dead yet" do not really look like a big advantage... :)



> Putting them into the ipi package is of advantage, so that plain python can also find the tests subdirectory. This way it is easy to test everywhere with a single line of code, such as explained e.g. here:
> python -c "import matplotlib; matplotlib.test()"
> 
> This can also be easy implemented for ipi, too.

This would work almost exactly the same, other than you should use: `python -c "import ipi_test; ipi_test.start()"` or something similar. Plain python can also import the test module once you sourced the env.sh file.

BTW, I have not strong opinions about the level of the `ipi_test` folder... just in several books and manuals they suggest to keep the test directory at the same level of the source directory. The only advantage I can see is that you can import them separately.

**Comment by ceriottm** [comment]
So @grhawk did you also convert the existing tests to py.test? I don't think it makes sense to have two infrastructures in the repo at the same time, and if you are convinced that py.test is suitable for what we need, I think it makes sense that you move everything to that framework - particularly since you'll be doing most of the regtest preparation work in the near future. I am closing this but feel free to reopen if further debate is needed.
