### ISSUE TITLE
gle4md generating piglet matrices

### ISSUE THREAD

**Issue by yantaow** [epfl-cosmo/i-pi-dev#154]
Dear i-Pi developers, 

On the website for generating piglet matrices, the generation assumes a beta_p sampling. However, is it possible to generate the matrices for which the MD actually runs at beta with the potential, sum_i V_i/P? Would  simply inputting the temperature as T/p accomplish this? 

Does anyone know, still on the piglet matrix generation, what the option, 

Centroid : OPT(H), Ns = 8, wmax/wmin = 10^4, 

means? 

Thanks very much, 
Yantao

**Comment by ceriottm** [comment]
Hello Yantao,
(1) the centroid refers to the (classical) thermostat applied to the
centroid degrees of freedom. The default (optimal-efficiency sampling)
should work well for most cases.
(2) it is possible to get PIGLET matrices for beta-sampled PIMD, but it is
not trivial. might be possible to use the existing matrices, but you have
to think how the T*(omega) curve that is derived in the beta_P framework
would transform in a beta framework. I doubt it is equivalent to a T
scaling but might be wrong. Bottom line - I don't have a turnkey solution
for this, and since it is just a different formulation of the identical
phase-space density, I don't think you'll find someone to do the
development for you....

**Comment by yantaow** [comment]
Dear Prof. Ceriotti, 

Thanks for the clarification. This makes a lot more sense. And I will stick with beta_p sampling then. 

Thanks again, 
Yantao 
________________________________________
